### ISSUE TITLE
Bathymetry output as integers not float 

### ISSUE THREAD

**Issue by maryjacketti** [castelao/oceansdb#12]
Every time I run the oceansdb module, the output is shown as an integer and not a float. For example, when I run:
import oceansdb
db = oceansdb.ETOPO()
db.keys()
h = db['topography'].extract(lat=15, lon=[25, 30, 38, 40, 45])
I get the output:
{'height': masked_array(data=[941, 504, 1012, 210, 1422],
             mask=[False, False, False, False, False],
       fill_value=999999,
            dtype=int32)}
Whereas, an example online that uses the same lat and lon get values as floats. 
Anyone know how to fix this?

**Comment by castelao** [comment]
Hi @maryjacketti , sorry for the delay. The difference in magnitudes might be related with the resolution of ETOPO being used. I remember to change it at some point the default option to high resolution and probably forgot to update the documentation. I need to double check that to confirm.

About the integer type, it shouldn't be a problem. I actually like that it's an integer since it's a smaller memory footprint and 1m is probably already too much vertical resolution for ETOPO. What do you think?

**Comment by maryjacketti** [comment]
So since we are using etopo5 and etopo1 has a much higher resolution, is it possible to use etopo1 instead of etopo5 or will it be too computationally heavy? I'm just not sure if using etopo5's resolution is high enough for my calculations.

**Comment by castelao** [comment]
Hi @maryjacketti , the default option is already the ETOPO 1min, and that is probably the output that you're getting. I updated the documentation, thanks for reporting that. Oh, and the reason for the data type is because the ETOPO 1min provides the elevation as an integer, while ETOPO 5min was float.
