### ISSUE TITLE
very different topography between 0.6.0 and 0.8.6

### ISSUE THREAD

**Issue by katieannemills** [castelao/oceansdb#13]
Check the altitude of a 1-degree, 5x5 grid of lat/long points centered on -67, 103;

`oceansdb==0.6.0` has most of these points at a couple kilometers above sea level;

`oceansdb==0.8.6` has many of them at or below sea level.

My first guess would be "ice versus no ice", but is that because that ice is actually gone, or is it because we're just not including it in the topo data in 0.8.6 (or something else entirely)? Thanks in advance!

**Comment by castelao** [comment]
Hi @BillMills , I'm so sorry. Somehow I missed this before! I'll check it on this weekend and get back to you.

**Comment by castelao** [comment]
The difference is that on 0.6 the default etopo was the 5 min arc resolution, while the 0.8 uses the more recent 1 min (bedrock).

Since the size of the files are 30 MB versus 890 MB, I'm moving back the default resolution to 5 min, and anyone interested in the high resolution should ask that explicitly, like

`ETOPO(resolution='1min')`

I might change CoTeDe to ask explicitly for the 1 min.

Thanks for the note, and I'm really sorry that I didn't answer before.
